#!/bin/bash

D=`realpath $0`
cd `dirname ${D}`

BUILD=`cat ver`
cat banner

echo "  ESA build ${BUILD}"
echo

source etc/esa

if [ "x${EVA_DIR}" != "x" ] ; then
    echo "EVA ICS directory: ${EVA_DIR}"
else
    echo "No EVA ICS directory defined. Setting to /opt/eva"
    EVA_DIR=/opt/eva
fi

export EVA_DIR

MNT_DIR=/tmp/eva-esa/mnt

mkdir -p ${MNT_DIR}

umount -f ${MNT_DIR} > /dev/null 2>&1

echo "Looking for command file [/eva-esa.json]"

for d in /dev/disk/by-uuid/*; do
    mount $d ${MNT_DIR} > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo -n "`echo ${d} | awk -F/ '{ print $NF }'` [`readlink ${d}|awk -F/ '{ print $NF }'`] - "
        if [ -f ${MNT_DIR}/eva-esa.json ]; then
            echo "processing..."
            rm -f ${MNT_DIR}/eva-esa.log
            i=0
            cmd=`cat ${MNT_DIR}/eva-esa.json |jq -r .exec[0]`
            until [ "x${cmd}" == "xnull" ]; do
                echo "command: ${cmd}" | tee -a ${MNT_DIR}/eva-esa.log
                echo ${cmd} | grep -E "[;|]" > /dev/null
                if [ $? -eq 0 ]; then
                    echo "Unsafe symbols found in command. Skipping" | tee -a ${MNT_DIR}/eva-esa.log
                    continue
                fi
                if [ -f `echo xc/${cmd}|awk '{ print $1 }'` ]; then
                    echo | tee -a ${MNT_DIR}/eva-esa.log
                    xc/${cmd} 2>&1 | tee -a ${MNT_DIR}/eva-esa.log
                    echo | tee -a ${MNT_DIR}/eva-esa.log
                else
                    echo "Command script file not found. Skipping" | tee -a ${MNT_DIR}/eva-esa.log
                fi
                i=`expr $i + 1`
                cmd=`cat ${MNT_DIR}/eva-esa.json |jq -r .exec[$i]`
            done
            rm -f ${MNT_DIR}/eva-esa.json
        else
            echo "none"
        fi
        umount ${MNT_DIR}
    fi
done

echo

if [ ! -x ${EVA_DIR}/sbin/eva-control ]; then
    echo "EVA ICS is not installed. Exiting"
    exit 5
else
    echo "EVA ICS v`${EVA_DIR}/sbin/eva-tinyapi -V` `${EVA_DIR}/sbin/eva-tinyapi -B`"
    echo
    ${EVA_DIR}/sbin/eva-control start
fi

exit 0
